Repository tanem/react-svg, pull requests merged in 2023-01, with the labels that each got.

#2116 Bump @rollup/plugin-terser
  package-lock.json
  package.json
  renovate.json
Labels: internal

#2060 Components don't work properly in iframe
  examples/iframe/.env
  examples/iframe/.gitignore
  examples/iframe/README.md
  examples/iframe/package-lock.json
  examples/iframe/package.json
  examples/iframe/public/index.html
  examples/iframe/public/svg.svg
  examples/iframe/src/index.js
  renovate.json
  src/ReactSVG.tsx
  src/owner-window.ts
Labels: bug

#2122 Add Iframe example to README
  README.md
Labels: documentation

#2125 Tweak type defs to fix styled-components issue
  README.md
  examples/styled-components/.env
  examples/styled-components/.gitignore
  examples/styled-components/README.md
  examples/styled-components/package-lock.json
  examples/styled-components/package.json
  examples/styled-components/public/index.html
  examples/styled-components/public/svg.svg
  examples/styled-components/src/index.tsx
  examples/styled-components/src/react-app-env.d.ts
  examples/styled-components/tsconfig.json
  examples/styled-components/tslint.json
  src/ReactSVG.tsx
  src/types.ts
Labels: bug

#1923 Add Error Handler to Limit Exception Bubbling
  MIGRATION.md
  README.md
  examples/api-usage/src/index.js
  examples/css-animation/src/index.js
  examples/fallbacks/public/svg.svg
  examples/fallbacks/src/index.js
  examples/styled-components/src/index.tsx
  package-lock.json
  src/ReactSVG.tsx
  src/types.ts
  test/__snapshots__/browser.spec.tsx.snap
  test/browser.spec.tsx
Labels: breaking
